[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
    { id = "check-added-large-files", exclude = { glob = [
        "docs/media/pycliche_wordmark-logo.xcf",
    ] } },
    { id = "check-docstring-first" },
    { id = "check-merge-conflict" },
    { id = "check-json" },
    { id = "check-toml" },
    { id = "check-yaml" },
    { id = "end-of-file-fixer" },
    { id = "no-commit-to-branch" },
    { id = "trailing-whitespace", args = [
        "--markdown-linebreak-ext",
        "md",
    ] },
    { id = "check-case-conflict" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.4"
hooks = [
    # `--config` to stop ruff from using {{project_name}}/pyproject.toml
    # https://github.com/astral-sh/ruff/issues/9585
    { id = "ruff-check", args = ["--fix", "--config", "pyproject.toml"] },
    { id = "ruff-format", args = ["--config", "pyproject.toml"] },
]

[[repos]]
repo = "https://github.com/DavidAnson/markdownlint-cli2"
rev = "v0.21.0"
hooks = [
    { id = "markdownlint-cli2", args = [
        "--config",
        ".markdownlint-cli2.yaml",
    ], language_version = "22.10.0" },
]

[[repos]]
repo = "https://github.com/crate-ci/typos"
rev = "v1.44.0"
hooks = [{ id = "typos", args = ["--force-exclude"] }]

[[repos]]
repo = "https://github.com/alessandrojcm/commitlint-pre-commit-hook"
rev = "v9.24.0"
hooks = [
    { id = "commitlint", stages = [
        "commit-msg",
    ], additional_dependencies = [
        "@commitlint/config-conventional",
    ] },
]
